# Generated by Django 3.1.4 on 2021-01-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myquora', '0011_answer_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, null=True, verbose_name='جنسیت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d', verbose_name='آواتار')),
                ('interests', models.ManyToManyField(blank=True, to='myquora.Category', verbose_name='علاقه مندی ها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'db_table': 'profile',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
