# Generated by Django 3.1.4 on 2020-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0004_auto_20201211_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=15, verbose_name='برچسب ها')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='tag_question',
            field=models.ManyToManyField(to='myquora.Tag', verbose_name='برچسب'),
        ),
    ]
