# Generated by Django 3.1.4 on 2020-12-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0005_auto_20201213_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامك'),
        ),
    ]
