# Generated by Django 3.1.4 on 2020-12-21 18:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0007_auto_20201221_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='متن جواب'),
        ),
    ]
