# Generated by Django 3.1.4 on 2020-12-27 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myquora', '0008_auto_20201221_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_like',
            field=models.ManyToManyField(blank=True, related_name='questions_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
