# Generated by Django 3.1.4 on 2021-01-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0011_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag_question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
