# Generated by Django 3.1.4 on 2021-01-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0012_auto_20210110_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=15, verbose_name='برچسب ها')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'db_table': 'tags',
                'ordering': ('created_time',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_tag',
            field=models.ManyToManyField(blank=True, to='myquora.Tag', verbose_name='برچسب'),
        ),
    ]
